const TYPES = {
  THEME_TOGGLE: "THEME_TOGGLE",
  DRAWER_TOGGLE: "DRAWER_TOGGLE",
  SET_USER_INFO: "SET_USER_INFO",
  SW_INIT: "SW_INIT",
  SW_UPDATE: "SW_UPDATE",
  UPDATE_SELECTED_GRP: "UPDATE_SELECTED_GRP",
};

export default TYPES;
